//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllerConnectInfo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllerConnectInfo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Column_ID {
            get {
                return ResourceManager.GetString("Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Column_Image {
            get {
                return ResourceManager.GetString("Column_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Column_IsReferenced {
            get {
                return ResourceManager.GetString("Column_IsReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local name.
        /// </summary>
        internal static string Column_LocalName {
            get {
                return ResourceManager.GetString("Column_LocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary name.
        /// </summary>
        internal static string Column_OrdinaryName {
            get {
                return ResourceManager.GetString("Column_OrdinaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image ID.
        /// </summary>
        internal static string Column_SymbolID {
            get {
                return ResourceManager.GetString("Column_SymbolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Column_ToolTip {
            get {
                return ResourceManager.GetString("Column_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Allergenes.
        /// </summary>
        internal static string NavigationBar_Allergens {
            get {
                return ResourceManager.GetString("NavigationBar_Allergens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Informations.
        /// </summary>
        internal static string NavigationBar_Informations {
            get {
                return ResourceManager.GetString("NavigationBar_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ingriedients.
        /// </summary>
        internal static string NavigationBar_Ingriedients {
            get {
                return ResourceManager.GetString("NavigationBar_Ingriedients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Products.
        /// </summary>
        internal static string NavigationBar_Products {
            get {
                return ResourceManager.GetString("NavigationBar_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string NavigationBar_Welcome {
            get {
                return ResourceManager.GetString("NavigationBar_Welcome", resourceCulture);
            }
        }
    }
}
